In [1]:
# 1) How-to-count-distance-to-the-previous-zero
#   For each value, 
#     count the difference back to the previous zero (or the start of the Series,whichever is closer)
#     create a new column 'Y'

#   Consider a DataFrame df where there is an integer column 'X'
#   import pandas as pd
#   df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

import pandas as pd
import numpy as np
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2,5, 0, 3, 4]})
zeroIndices = df.index[df.X == 0]
Yvalues = []
j=len(zeroIndices)-1
for i in reversed(range(len(df.X))):
    if(i< zeroIndices[j]):
        Yvalues.append(i+1)
    elif (i==zeroIndices[j]):
        Yvalues.append(0)
        j-=1
    elif (i>zeroIndices[j]):
        Yvalues.append(i - zeroIndices[j])
        
Yvalues.reverse() 
df["Y"] = Yvalues
df

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

In [2]:
# 2) Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series 's' of random numbers.

dateTimeIndex= pd.date_range(start="01/01/2015", end="31/12/2015", freq="B") # Creating a DateTime List for all business days
s = pd.Series(np.random.randint(0,10000,size=len(dateTimeIndex)), index=dateTimeIndex, name="RandNumbers")
print(s)

2015-01-01    8283
2015-01-02    2041
2015-01-05    4580
2015-01-06    3449
2015-01-07    4985
2015-01-08    8378
2015-01-09    8731
2015-01-12    9103
2015-01-13    2142
2015-01-14    9410
2015-01-15    2778
2015-01-16    7218
2015-01-19    3055
2015-01-20    4887
2015-01-21     417
2015-01-22    6149
2015-01-23    1305
2015-01-26    9370
2015-01-27    6417
2015-01-28    7286
2015-01-29    7566
2015-01-30    7300
2015-02-02    5831
2015-02-03    6240
2015-02-04    6273
2015-02-05    9543
2015-02-06     782
2015-02-09    3409
2015-02-10    9703
2015-02-11    1968
              ...
2015-11-20    5141
2015-11-23    8329
2015-11-24    3328
2015-11-25    6504
2015-11-26    9438
2015-11-27    8590
2015-11-30    7072
2015-12-01    4136
2015-12-02    1446
2015-12-03    4629
2015-12-04    1919
2015-12-07     229
2015-12-08    8519
2015-12-09    3437
2015-12-10    9151
2015-12-11    6737
2015-12-14    9730
2015-12-15    6323
2015-12-16    7686
2015-12-17    6101
2015-12-18    3050
2015-12-21    4393
2015-12-22    3745
2015-12-23    7546
2015-12-24    5700
2015-12-25    3851
2015-12-28    5495
2015-12-29     542
2015-12-30    7924
2015-12-31    3779
Freq: B, Name: RandNumbers, Length: 261, dtype: int32

In [3]:
# 3) Find the sum of the values in s for every Wednesday

allWednesdaySum = s[s.index.day ==2].sum() #Adding all the random numbers associated with every wednesday of the year
print("Sum of all random numbers on wednesday in 2015: ", allWednesdaySum)
print()

# 4) Average For each calendar month

monthlyAverage = [s[s.index.month == i].mean() for i in range(1,13)] #Calculating the average for every month
print("Average of every Calender Month: ", np.around(monthlyAverage, 2)) # Formatting the averages in list to show precision of 2 decimal points
print()

# 5) For each group of four consecutive calendar months in s, find the date on which the highest value occurred.

fourMonthHighestDates = s.index[s.isin(s.groupby([((s.index.month -1)/4).astype("int64", copy=True)] ).max())]
print("Dates for which the highest value occured in every 4 months in 2015  along with the values: ")
fourMonthHighestDates

Sum of all random numbers on wednesday in 2015:  47558

Average of every Calender Month:  [5675.   4877.15 4653.95 4576.09 5230.14 5752.05 4314.83 4458.19 4348.41
 5114.05 5455.95 5046.43]

Dates for which the highest value occured in every 4 months in 2015  along with the values:

DatetimeIndex(['2015-04-06', '2015-06-18', '2015-12-14'], dtype='datetime64[ns]', freq=None)